"""empty message

Revision ID: 8fb71ba7a6b9
Revises: 6957380aa343
Create Date: 2024-10-13 20:39:21.269686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb71ba7a6b9'
down_revision = '6957380aa343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ayah', schema=None) as batch_op:
        batch_op.alter_column('surah_name_roman',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ayah', schema=None) as batch_op:
        batch_op.alter_column('surah_name_roman',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
