"""timestamp memorized ayah table

Revision ID: 907758551b47
Revises: 8fb71ba7a6b9
Create Date: 2024-10-14 16:50:57.550119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907758551b47'
down_revision = '8fb71ba7a6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ayah', schema=None) as batch_op:
        batch_op.alter_column('timestamp_memorized',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('memorization_user_ayah', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_memorized', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorization_user_ayah', schema=None) as batch_op:
        batch_op.drop_column('timestamp_memorized')

    with op.batch_alter_table('ayah', schema=None) as batch_op:
        batch_op.alter_column('timestamp_memorized',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
