"""Initial migration.

Revision ID: bf47899a05b4
Revises: 
Create Date: 2024-10-13 19:26:36.220645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf47899a05b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memorization_user')
    with op.batch_alter_table('ayah', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('surah_name_roman',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('surah_no',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('juz_no',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ayah_no_surah',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ayah_memorized',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ayah_ar',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('ayah_no_quran',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_quran_data_index')
        batch_op.create_unique_constraint(None, ['ayah_no_quran'])
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'surah', ['surah_no'], ['surah_no'])
        batch_op.drop_column('ayah_en')
        batch_op.drop_column('sajdah_ayah')
        batch_op.drop_column('list_of_words')
        batch_op.drop_column('manzil_no')
        batch_op.drop_column('hizb_quarter')
        batch_op.drop_column('sajdah_no')
        batch_op.drop_column('ruko_no')
        batch_op.drop_column('no_of_word_ayah')

    with op.batch_alter_table('memorization_user_ayah', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ayah_memorized', sa.Integer(), nullable=False))

    with op.batch_alter_table('surah', schema=None) as batch_op:
        batch_op.alter_column('surah_no',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_ayah_surah',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('juz_no',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('surah_name_roman',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('surah_name_en',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('surah_name_ar',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('place_of_revelation',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('surah_memorized',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surah', schema=None) as batch_op:
        batch_op.alter_column('surah_memorized',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('place_of_revelation',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('surah_name_ar',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('surah_name_en',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('surah_name_roman',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('juz_no',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('total_ayah_surah',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('surah_no',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('memorization_user_ayah', schema=None) as batch_op:
        batch_op.drop_column('ayah_memorized')

    with op.batch_alter_table('ayah', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_word_ayah', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ruko_no', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sajdah_no', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('hizb_quarter', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('manzil_no', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('list_of_words', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('sajdah_ayah', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ayah_en', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_quran_data_index', ['id'], unique=False)
        batch_op.alter_column('ayah_no_quran',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ayah_ar',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ayah_memorized',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ayah_no_surah',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('juz_no',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('surah_no',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('surah_name_roman',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('memorization_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
